Fix/dynamic stringfied body to bearer auth
Coaktion/client-core pull request #81
Opened 2024-07-30 16:49 UTC by andaraGui

**Descrição:**
 - Transformando o tipo de dado da requisição de autenticação conforme especificado na criação do autenticador do client.
 - Adicioinando validação do conteúdo "message" dos erros capturados, pois recebia type error se a mensagem da requisição  não estivesse formatada com o atributo "message".

**Alterações no código (opcional):**

- _Uma lista das principais mudanças de código que foram feitas._
- _Ao descrever as mudanças de código, tente comunicar **como** e **por que** você implementou algo de uma maneira específica, não só **o que** mudou._

---

**Checklist:**

- [x] Meu código segue o estilo de código deste projeto.
- [x] Minha mudança requer uma alteração na documentação.
- [x] Eu atualizei a documentação conforme necessário.
- [x] Eu li o documento **CONTRIBUTING**.
- [x] Eu adicionei testes para cobrir minhas alterações.
- [x] Todos os testes novos e existentes passaram.

2024-07-31 18:08 UTC, gabrielh-silvestre requested changes

2024-07-31 18:08 UTC, gabrielh-silvestre commented on tests/zendesk.test.ts
> +      await zendeskClientBase.makeRequest(payload);
Fala @andaraGui, apenas um detalhe, quando o teste eperar um erro é melhor utilizar o `expect().toThrow()`, pois se a função só executar sem problemas nesse contexto (`try/catch`), o teste simplesmente vai passar, mesmo que nenhum `expect` tenha sido chamado.

2024-08-01 11:33 UTC, andaraGui commented on tests/zendesk.test.ts
> +      await zendeskClientBase.makeRequest(payload);
Boa, Gab! Ainda deixou passar alguns pontos desse tipo em relação a testes.

Vou fazer a alteração aqui, brigadão pelo toque!

2024-08-02 14:07 UTC, JoaoMacedo03 approved these changes

2024-08-05 18:13 UTC, gabrielh-silvestre approved these changes

2024-08-05 18:13 UTC, merged